### ISSUE TITLE
certain packages missing on Windows - needed to install in pip/edit Pipfile

### ISSUE THREAD

**Issue by branmkam** [Geovation/usemap-rest#10]
As a Windows user I needed to install these packages into pip and pipenv in order for them to register.
![image](https://user-images.githubusercontent.com/54331071/193007084-05d5059b-0b0f-49bc-ab6b-efb4c1161a4d.png)
These were initially not colored and were not registered as modules until I manually installed them using pip and pipenv.

On the pipfile-edited branch, my app works after having installed these packages, which are present in the pipfile.
![image](https://user-images.githubusercontent.com/54331071/193007597-c17e9b6f-f4d7-457b-98a7-73e4ba67ac02.png)

**Comment by DaveBathnes** [comment]
I think we need more information on this. These packages are already in the pipfile?

Installing with pip can be deceptive locally - you may have installed using pip so it is now working on your machine, but not through a virtual environment.

The only changes I can see from the branch are an update to the python version which we can't do without checking that it's supported where the app is deployed (and where we want to deploy it)

**Comment by branmkam** [comment]
I see - they must have already been present in the Pipfile and just not on my machine...
It's odd then that they didn't install upon cloning the repo.

**Comment by DaveBathnes** [comment]
They won't install on cloning the repo, they are installed by running ```pipenv install``` and then running that virtual environment. It's possible you've installed using pip and then are running flask locally on your machine rather than in a virtual environment?

On creating issues, document the problem rather than the proposed fix (or both). So initially you were having an error on running flask which was saying that dotenv wasn't available?

**Comment by branmkam** [comment]
it could be - i haven't run it with pipenv and flask in the same command line - I used `pipenv shell` then did `flask run -h 0.0.0.0`

**Comment by branmkam** [comment]
Interesting news - I started without anything else straight from main - and after running 
`export FLASK_APP=./mapup/index.py
export FLASK_ENV=development
pipenv shell
flask run -h 0.0.0.0`

it worked perfectly. I guess we just need to tell Windows users to `pip install flask`, python-dotenv`, and `requests`

**Comment by branmkam** [comment]
yes - I did both for all three modules (updated above)

**Comment by DaveBathnes** [comment]
OK, I'm still confused, you should need to simply run ```pipenv install``` (not listing the modules).

But if all working that's good!

**Comment by branmkam** [comment]
AH! I thought you had to install each individually - does `pipenv install` check what's in the Pipfile?

**Comment by DaveBathnes** [comment]
Yes, it's like ```npm install``` or similar processes. The idea is that it sets up a virtual environment with the required dependencies.

**Comment by branmkam** [comment]
ok perfect - we can close this then. I just hadn't used `pipenv` before so sorry for the confusion.

**Comment by branmkam** [comment]
closed - windows users just need to `pipenv install`
